services:
  bot:
    build:
      context: ..
      dockerfile: .docker/Dockerfile
    env_file:
      - ../.env
    volumes:
      - ../src:/app/src
    command: ["poetry", "run", "python", "src/app.py"]
